::  
:: THIS SCRIPT WILL UPLOAD THE TRIPLES INTO A REPOSITORY ON YOUR GRAPHDB
:: IN THIS CASE WE WILL USE GRAPH DB HOSTED ON THE LOCAL HOST
:: VARIABLES THAT NEED TO BE DEFINED WHEN RUNNING THE SCRIPT:
::  GRAPHDB_BIN --> DIRECTORY WHERE THE GRAPH DB EXECUTABLES ARE
:: RDF_IN --> DIRECTORY WHERE THE TRIPLES ARE (.TTL FILES)
:: REPO --> NAME OF THE REPOSITORY ON GRAPHDB
:: EXAMPLE OF USAGE: RDF.BAT "C:\Users\alberto.traverso\SW\graphdb-free-8.11.0\bin" "C:\Users\alberto.traverso\Workspace_RO\Data\RDFOutput" "RO_Test_IBSI" "C:\Users\alberto.traverso\Workspace_RO\Scripts\D2RQ\MappingScripts\Executables\repoconfig.ttl"
@ECHO OFF
:: DEFINING VARIABLES
SET GRAPHDB_BIN=%1
SET RDF_IN=%2
SET REPO=%3
SET REPO_CONFIG=%4
ECHO %GRAPHDB_BIN%
ECHO %RDF_IN%
ECHO %REPO%
ECHO %REPO_CONFIG%
:: LOOP IN THE DIRECTORY FOR ALL THE .TTL FILES AND LOAD TRIPLES

CALL %GRAPHDB_BIN%\loadrdf -c %REPO_CONFIG% -m parallel %RDF_IN%
